config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'homes_about'
  devise_for :users
  resources :books
  resources :users, only: [:show, :edit, :update, :index, :create, :update]
  post '/users/:id' => 'users#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200 }

  belongs_to :user

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord

  belongs_to :user
  attachment :image
  has_many :post_comments, dependent: :destroy

  validates :shop_name, presence: true
  validates :image, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 20 }
  validates :introduction, length: {maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
   user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name ,:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :current_user!, only: [:edit, :update]


  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
   @book_new = Book.new
   @book = Book.find(params[:id])
   @user = @book.user
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
    flash[:success] = 'Book was successfully created.'
    redirect_to book_path(@book)
    else
    @user = current_user
    render :index
    end
  end

  def edit
    @book = Book.find(params[:id])

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:success] = 'Book was successfully updated.'
    redirect_to book_path(@book)
    else
    render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def current_user!
    @book = Book.find(params[:id])
    if @book.user != current_user
    redirect_to books_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    post_image = PostImage.find(params[:post_image_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_image_id = post_image.id
    comment.save
    redirect_to post_image_path(post_image)
  end

  def destroy
    PostComment.find_by(id: params[:id], post_image_id: params[:post_image_id]).destroy
    redirect_to post_image_path(params[:post_image_id])

  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController

  def new
    @post_image = PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to post_images_path
    else
      render :new
    end
  end

  def index
    @post_images = PostImage.all
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end

  private

  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.reverse_order
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
    redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:success] = 'Book was successfully updated.'
    redirect_to user_path(@user.id)
    else
    render :edit
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image,:introduction )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
 <div class='container px-5 px-sm-0'>
 <div class='row'>
 <div class='col-md-3'>

  <h1>Editing Book</h1>

   <% if @book.errors.any? %>
    <%= @book.errors.count %>件のerrorが発生しました
     <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
   <% end %>

  <%= form_with model:@book, local:true do |f| %>

  <div class="form-group">
    <label for="book_title" style="display:block">Title</label>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <label for="book_opinion" style="display:block">Opinion</label>
    <%= f.text_area :body %>
  </div>

  <div class="form-group">
   <%= f.submit 'Update Book' ,class:"btn btn-success"%>
  </div>

 <% end %>

   <tr>
    <td><%= link_to "Show", book_path(@book) %></td>
    <td><%= link_to "Back", books_path %></td>
   </tr>

  </div>
 </div>
</div>

app/views/books/index.html.erb
<main>
 <div class='container px-5 px-sm-0'>
 <div class='row'>
 <div class='col-md-3'>

     <% if @book.errors.any? %>
    <%= @book.errors.count %>件のerrorが発生しました
     <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
   <% end %>

  <h2>User info</h2>
   <table class='table'>

    <%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>


   <tr>
	   <th>name</th>
    <td><%= current_user.name %></td>
   </tr>

   <tr>
	   <th>introduction</th>
	   <td><%= current_user.introduction %></td>

   </tr>

   </table>

 <div class='row'>
  <%= link_to edit_user_path(current_user.id) ,class:"btn btn-outline-secondary btn-block" do %>
  <i class="fas fa-user-cog"></i>
  <% end %>

 </div>

  <h2 class="mt-3">New book</h2>

  <%= form_with model: @book, url: books_path, local:true do |f| %>

  <div class="form-group">
    <label for="book_title">Title</label>

    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body %>
  </div>

  <div class="form-group">
   <%= f.submit 'Create Book' ,class:"btn btn-success"%>
  </div>

 <% end %>



  </form>
  </div>

  <div class='col-md-8 offset-md-1'>
   <h2>Books</h2>
    <table class="table bookshelf">

     <thead>
      <tr>
       <td> </td>
       <td>Title</td>
       <td>Opinion</td>
       <td colspan="3"></td>
      </tr>
     </thead>

     <tbody>
      <% @books.each do |book| %>

      <tr>
       <td><%= link_to user_path(book.user.id) do %>
           <%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
           <% end %>
       </td>

       <td><%= link_to book_path(book.id) do %><%= book.title %>
           <% end %>
       </td>

       <td><%= book.body %></td>
       <td colspan="3"></td>
      </tr>

      <% end %>

     </tbody>

    </table>
   </div>
  </div>
 </div>
</main>

app/views/books/show.html.erb
<main>
 <div class='container px-5 px-sm-0'>
 <div class='row'>
 <div class='col-md-3'>

  <h2>User info</h2>
   <table class='table'>

    <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>

    
    
   <tr>
	   <th>name</th>
    <th><%= @user.name %></th>
   </tr>

   <tr>
	   <th>introduction</th>
	   <th><%= @user.introduction %></th>
   </tr>

   </table>

 <div class='row'>
  <%= link_to edit_user_path(@book.user.id) ,class:"btn btn-outline-secondary btn-block" do %>
  <i class="fas fa-user-cog"></i>
  <% end %>

 </div>

  <h2 class="mt-3">New book</h2>

  <%= form_with model:@book_new, url: books_path, method: :post,local:true do |f| %>

  <div class="form-group">
    <label for="book_title" style="display:block">Title</label>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <label for="book_opinion" style="display:block">Opinion</label>
    <%= f.text_area :body %>
  </div>

  <div class="form-group">
   <%= f.submit 'Create Book' ,class:"btn btn-success"%>
  </div>

 <% end %>



  </form>
  </div>

  <div class='col-md-8 offset-md-1'>
   <h2>Book detail</h2>
    <table class='table table-hover table-inverse'>

      <tr>
       <td><%= link_to user_path(@book.user) do %>
           <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %><br>
           <%= @book.user.name %>
           <% end %>
       </td>

       <td><%= link_to @book.title, book_path(@book) %></td>
       <td><%= @book.body %></td>

       <% if @book.user == current_user %>
       <td><%= link_to "Edit", edit_book_path(@book), class: 'btn btn-success' %></td>
       <td><%= link_to "Destroy", book_path(@book), class: 'btn btn-danger', method: :delete, data: { confirm: "Are you sure?" } %></td>
       <% end %>

       <td colspan="3"></td>
      </tr>
    </table>
   </div>
  </div>
 </div>
</main>

app/views/homes/about.html.erb
<main>

 <p id="notice"></p>
  <div class="container">
   <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>

 <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !</h1>

    </div>
   </div>
  </div>

</main>

app/views/homes/top.html.erb
<main>
    <p id="notice"></p>
    <div class="container">
    <div class="row">
    <div class='mx-auto'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" <%= link_to "Log in", new_user_session_path, class: "menu" %></a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" <%= link_to "Sign Up", new_user_registration_path, class: "menu" %></a>
        </div>
      </div>
    </div>
  </div>
</div>


</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
       <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">



            <% if user_signed_in? %>

            <li class="nav-item">
             <%= link_to ' Home', user_path(current_user.id), class: 'fas fa-home nav-link text-white' %>
            </li>

            <li class="nav-item">
             <%= link_to " Users", users_path, class: 'fas fa-users nav-link text-white' %>
            </li>

            <li class="nav-item">
             <%= link_to ' Books', books_path, class: 'fas fa-book-open nav-link text-white' %>
            </li>

            <li class="nav-item">
             <%= link_to " logout", destroy_user_session_path, class: 'fas fa-sign-out-alt nav-link text-white', method: :delete %>
            </li>



            <% else %>
            <li class="nav-item">
             <%= link_to ' Home', root_path, class: 'fas fa-home nav-link text-white' %>
            </li>

            <li class="nav-item">
             <%= link_to " About", homes_about_path, class: 'fas fa-link nav-link text-white' %>
            </li>

           <li class="nav-item">
            <%= link_to " sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-white' %>
           </li>

           <li class="nav-item">
            <%= link_to " login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-white' %>
           </li>

           <% end %>

            </ul>
          </div>
        </div>
     </nav>

    </header>

<% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

<%= yield %>

<footer>
  <div class='container mt-5'>
   <div class='row'>
    <div class='mx-auto'>
     <p>CopyRight Infratop.inc</p>
    </div>
   </div>
  </div>
</footer>

  </body>
</html>

app/views/post_images/index.html.erb
<% @post_images.each do |post_image| %>
<div>
 <%= link_to post_image_path(post_image.id) do %>

  <%= attachment_image_tag post_image, :image %>

 <% end %>

  <p>投稿ユーザー画像：<%= attachment_image_tag post_image.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></p>
  <p>ショップ名：<%= post_image.shop_name %></p>
  <p>説明：<%= post_image.caption %></p>
  <p>ユーザーネーム：<%= post_image.user.name %></p>
  <p><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id) %></p>
</div>
<% end %>

app/views/post_images/new.html.erb
<h1>画像投稿フォーム</h1>
<% if @post_image.errors.any? %>
  <%= @post_image.errors.count %>件のエラーが発生しました
  <% @post_image.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_with model: @post_image, local:true do |f| %>
  <h4>画像</h4>
  <%= f.attachment_field :image %>
  <h4>ショップ名</h4>
  <%= f.text_field :shop_name %>
  <h4>説明</h4>
  <%= f.text_area :caption %>
  <%= f.submit '投稿' %>
<% end %>

app/views/post_images/show.html.erb
<div>
  <%= attachment_image_tag @post_image, :image %>
  <p>ショップ名：<%= @post_image.shop_name %></p>
  <p>説明：<%= @post_image.caption %></p>
  <p>ユーザーネーム：<%= @post_image.user.name %></p>
  <p>投稿日時：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
  <% if @post_image.user == current_user %>
    <%= link_to "削除", post_image_path(@post_image), method: :delete %>
  <% end %>

</div>

<div>
<p>コメント件数：<%= @post_image.post_comments.count %></p>
<% @post_image.post_comments.each do |post_comment| %>
  <p><%= attachment_image_tag post_image.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></p>
  <%= post_comment.user.name %>
  <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
  <% if post_comment.user == current_user %>
  <div>
    <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete %>
  </div>
  <% end %>

<% end %>
</div>
<div>
<%= form_with(model:[@post_image, @post_comment], local: true) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
<% end %>
</div>

app/views/users/edit.html.erb
<main>

 <p id="notice"></p>
  <div class="container">
   <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>

    <h2>User info</h2>
 　 　<%= form_with model:@user, local:true do |f| %>

 　   <% if @user.errors.any? %>
     <%= @user.errors.count %>件のerrorが発生しました
     <% @user.errors.full_messages.each do |message| %>
      <%= message %>
     <% end %>
    <% end %>

 　  <div>
     <%= f.label :name %><br>
     <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
    </div>

    <div>
     <%= f.label :image %><br>
     <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
    </div>

    <div>
     <%= f.label :introduction %><br>
     <%= f.text_area :introduction %>
    </div>

     <%= f.submit "Update User" %>
　   <% end %>

    </div>
   </div>
  </div>

</main>

app/views/users/index.html.erb
<main>
 <div class='container px-5 px-sm-0'>
 <div class='row'>
 <div class='col-md-3'>

  <h2>User info</h2>
   <table class='table'>

    <%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>


   <tr>
	   <th>name</th>
    <td><%= current_user.name %></td>
   </tr>

   <tr>
	   <th>introduction</th>
	   <td><%= current_user.introduction %></td>
   </tr>

   </table>

 <div class='row'>
  <%= link_to edit_user_path(current_user.id) ,class:"btn btn-outline-secondary btn-block" do %>
  <i class="fas fa-user-cog"></i>
  <% end %>

 </div>

  <h2 class="mt-3">New book</h2>

  <%= form_with model:@book, local:true do |f| %>

  <div class="form-group">
    <label for="book_title" style="display:block">Title</label>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <label for="book_opinion" style="display:block">Opinion</label>
    <%= f.text_area :body %>
  </div>

  <div class="form-group">
   <%= f.submit 'Create Book' ,class:"btn btn-success"%>
  </div>

 <% end %>



  </form>
  </div>

  <div class='col-md-8 offset-md-1'>
   <h2>Users</h2>
    <table class='table table-hover table-inverse'>
     <thead>
      <tr>
       <td colspan="3"></td>
       <td>image</td>
       <td>name</td>
      </tr>
     </thead>

     <tbody>
      <% @users.each do |user| %>

      <tr>
       <td colspan="3"></td>
       <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg",size:'60x60' %></td>
       <td><%= user.name %></td>
       <td><%= link_to "Show", user_path(user.id) %></td>

      </tr>

      <% end %>

     </tbody>

    </table>
   </div>
  </div>
 </div>
</main>

app/views/users/show.html.erb
<main>
 <p id="notice"></p>
 <div class='container px-5 px-sm-0'>
 <div class='row'>
 <div class='col-md-3'>

  <h2>User info</h2>
   <table class='table'>

    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>

   <tr>
	   <th>name</th>
    <td><%= @user.name %></td>
   </tr>

   <tr>
	   <th>introduction</th>
	   <th><%= @user.introduction %></th>
   </tr>

   </table>

 <div class='row'>
  <%= link_to edit_user_path(@user.id) ,class:"btn btn-outline-secondary btn-block" do %>

  <i class="fas fa-user-cog"></i>
  <% end %>

 </div>

  <h2 class="mt-3">New book</h2>

  <%= form_with model:@book, local:true do |f| %>

  <div class="form-group">
    <label for="book_title" style="display:block">Title</label>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <label for="book_opinion" style="display:block">Opinion</label>
    <%= f.text_area :body %>
  </div>

  <div class="form-group">
   <%= f.submit 'Create Book' ,class:"btn btn-success"%>
  </div>

 <% end %>



  </form>
  </div>

  <div class='col-md-8 offset-md-1'>
   <h2>Books</h2>
    <table class='table table-hover table-inverse'>
     <thead>
      <tr>
       <th>Title</th>
       <th>Opinion</th>
       <th colspan="3"></th>
      </tr>
     </thead>

     <tbody>
      <% @books.each do |book| %>

      <tr>
       <td><%= link_to user_path(book.user.id) do %>
           <%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
           <% end %>
       </td>

       <td><%= link_to book_path(book.id) do %><%= book.title %>
           <% end %>
       </td>

       <td><%= book.body %></td>
       <td colspan="3"></td>
      </tr>

      <% end %>

     </tbody>

    </table>
   </div>
  </div>
 </div>
</main>